#!/bin/bash

if [ "$#" -eq 0 ]; then
	echo "Specify at least one user"
        exit 1
fi

# variables
users="$@"
	
# creation of users
for user in $users; do
	if id "$user" &> /dev/null; then
		echo "This user already exists"
	else
		sudo useradd -m "$user" --shell /bin/bash
		echo "$user:soleil1234" | chpasswd
		echo "$user is created"
	fi
done

exit 0
