#!/bin/bash

if [[ $# == 0 ]];then
    echo "You should add some arguments"
    exit 1
fi

default_password="soleil1234"

for user in "$@"
do
    if getent passwd "$user" > /dev/null 2>&1; then
        echo "L'utilisateur $user existe déja"
    else
        sudo useradd -m "$user" && echo "$user:$defaultpassword" | sudo chpasswd

        if [$? -eq 0]
            echo "L'utilisateur $user a été créé avec un mot de passe par défaut : $defaultpassword"
        else
            echo "L'utilisateur n'a pas été créé"
        fi
    fi
done
