#!/bin/bash

# Verifier si utilisateur en argument
if [[ $# -eq 0 ]]; then
	echo "il n'y a pas d'utilisateurs en argument de commande script"
	exit 1
fi

# boucle pour les utilisateurs
for utilisateur in $*;
do
	# Verifier si id utilisateur existe
	if id "$utilisateur" &>/dev/null;
	then
		echo "l'utilisateur "$utilisateur" existe déjà"
	else
		#creer l'utilisateur avec repertoire home (-m) et mot de passe par defaut soleil1234"
		# install de whois pour commande mkpasswd
		sudo useradd -m -p $(mkpasswd soleil1234) "$utilisateur"
		# on verifie si la sortie de la derniere commande: si 0, cde ok
		if [ $? -eq 0 ]; then
			echo "l'utilisateur est crée"
		fi
	fi
done

exit 0
