#!/bin/bash

if [[ $# -le 0 ]]; then
	echo "Rentrez un nom d'utilisateur"
	exit 1
fi 

users="$@"
password="soleil1234"

for users in $users; do
	sudo useradd $users --create-home -p $password &>/dev/null
	if [[ $? = 0 ]]; then
		echo "Utilisateur $users créé"
	else	
		echo "L'utilisateur $users existe déja"
	fi
done

exit 0
