#!/bin/bash

if [[ $# -le 0 ]]; then
	echo "Rentrez un nom d'utilisateur"
	exit
fi 

users=$@
password="soleil1234"
count=1

while [[ $count -le $# ]]; do
	for users in $users; do
		sudo useradd $users --create-home -p $password &> /dev/null 
			if [[ $? = 0 ]]; then
				echo "Utilisateur $users créé"
			else	
				echo "L'utilisateur $users existe déja"
			fi
		count=$(($count+1))
	done
done